nextgen:
  initiative: nextgen
  domain: openshiftapps
  baseImageRegistry: docker-registry.default.svc:5000
  imageRegistryNamespace: app-shared-services
  repoURL: wcgartifactory-docker.jfrog.io
  routerID: 4c8f
  clusterID: wc-sb01
  conjurAccount: wellcare
  conjurHostID: authn-k8s/tampa

application: premium-billing
replicaCount: 2

imageStreams:
  service:
    name: ss-notes-ui
    pullPolicy: Always
  nginxPromExp:
      tag: 0.5.0
prometheusPath: /metrics
prometheusPort: 9081

service:
  httpPort: 8081
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8081
    name: http

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: {}

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

env:
    service:

conjurSecrets: {}

resources:
 limits:
   cpu: 200m
   memory: 500M
 requests:
   cpu: 10m
   memory: 32M

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 25
  periodSeconds: 3
  path: /
  port: 8081
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 25
  periodSeconds: 3
  path: /
  port: 8081

nodeSelector: {}

tolerations: []

affinity: {}

deploymentStrategy:
  revisionHistoryLimit: 3
  maxSurge: 1
  maxUnavailable: 1
  type: RollingUpdate

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""